### ISSUE TITLE
`findORFs` should ignore internal, in-frame start codons

### ISSUE THREAD

**Issue by arendsee** [JokingHero/ORFik#57]
`findORFs` by default finds every ORF, thus a sequence like this:

```
ATG ATG ATG TTT TGA
```
where ATG is a start codon and TGA is a stop codon, would yield 3 ORFs. A user would probably instead want a single ORF to be reported: the longest one.

Setting `longestORF=TRUE` partially fixes this problem, returning a single ORF for the case above, as expected.

But with `longestORF=TRUE`, out-of-frame overlaps are lost. For example:

```
ATG TAT GTT TGA TTT GA
^    ^      ^     ^
|    ` -----|-----'
'-----------'
```

contains two valid ORFs that overlap in different frames, but `findORFs` with `longestORF=TRUE` returns only one of them. There are many cases of overlapping ORFs in nature, so I think these should be preserved.

I suggest that keeping only the longest in-frame ORFs should be the default behavior. Then there should be an option to remove overlapping out-of-frame ORFs. This change would make `ORFik` more consistent with the users expectations and with other tools such as `getorf` from the EMBOSS package.

**Comment by Roleren** [comment]
Funny you bring that up, look at the MakeItMoreLogical branch on github, I have tried to implement this behaviour in the branch that will be merged in a few days. 

Here is my idea, I have function called longestORF() that gives you the longest orf per unique
(seqname, strand, stop codon) combination, that is what you are talking about.

So to get what you want, you could do now on devel:
res <- findORFs(seqs, longestORF = FALSE)
res <- longestORF(res)

But as you say, I should put the longestORF function inside findORFs, maybe as this ?

argument is called: collapseORF = TRUE/FALSE  ( If true, call longestORF() )
argument is called: longestORF = TRUE/FALSE ( If true, call maxORFPerSequence)

Now for logic of the findORFs function, the longestORF function will be put inside:
How it is now:
findORFs(seqs, startCodon = startDefinition(1),
  stopCodon = stopDefinition(1), longestORF = FALSE,
  minimumLength = 0)

How it will be:
findORFs(seqs, startCodon = startDefinition(1),
  stopCodon = stopDefinition(1), collapseORF = TRUE, 
  longestORF = FALSE, minimumLength = 0)

Do you have an idea of more logical names than collapseORF and longestORF ? 
Maybe longestORFper, or longestExtensionORF etc.

**Comment by arendsee** [comment]
Cool that this is already under development! I definitely like the idea of adding a strand column to the output.

Having two flags, `longestORF` and `collapseORF`, that determine which function is called is a little confusing to me. What if both are set to true? You could alternatively have a single argument, `mode`, which could take the values `all`, `longest`, and `collapse`. Though I don't like this either, since string arguments are messy.

I prefer your current approach with the two filters `longestORF` and `maxORFPerSequence`. This is a simpler solution and goes along nicely with the pipeline style of programming. For example, with `magrittr`, we might write:

```R
findORFs(seqs) %>% longestORF
```

My one misgiving about this filtering approach is that the performance might be bad.

Unless you have a use case in mind where someone might want every nested ORFs, I actually favor returning only the longest ORFs for each frame.

**Comment by Roleren** [comment]
In my research I use all nested ORFs, I look for functional uORFs, so the implementation has been a bit biased towards my own needs, hehe :)

**Comment by arendsee** [comment]
That makes sense.

I'll play around with the functions in `dev` branch later this week and then get back with you.

**Comment by Roleren** [comment]
Ok, we have discussed this on our end now, new version will be: 

findORFs(seqs, startCodon = startDefinition(1),
stopCodon = stopDefinition(1), longestORF = TRUE,
minimumLength = 0)

Where longestORF means longest ORF per stopcodon, does that sound good ?

**Comment by arendsee** [comment]
So, with `longestORF=TRUE`, the algorithm would identify each stop in all 3 forward frames and then for each stop trace backwards to the most distant start or stop codon (throwing out the ORF in the latter case).

If I understand this correctly, then it is exactly what I was looking for.

**Comment by Roleren** [comment]
Good, and it should be super fast now, a pure for loop in c++, is so fast, it's not even funny. The algorithm is n*log(n).
