### ISSUE TITLE
RNAseq strand information in calculating Translation efficiency

### ISSUE THREAD

**Issue by sunyumail93** [JokingHero/ORFik#86]
Hello,

Thanks for creating this wonderful tool. I am trying to use translationalEff in my research, and my RNAseq library is stranded. I realized that your function only looks for reads mapped to the sense direction of the transcripts, while in my stranded library, most of the reads mapped to the reverse strand, and I missed those correct reads. Could you provide some help on this? Thank you! I used RNAseq bam file as input.

**Comment by Roleren** [comment]
Hey, if you do strand(rna) <- "*", it will set them to match in both directions. Is that what you wanted ? :)

**Comment by sunyumail93** [comment]
> Hey, if you do strand(rna) <- "*", it will set them to match in both directions. Is that what you wanted ? :)

Hi,

Thanks for your reply. I actually wanted to count the reads mapped to the antisense strand of the transcribed RNA. If there is a place to input the library type (for example, fr-firststrand, fr-secondstrand) that would be ideal. Or, if I can reverse the strand info of all the reads (I don't know how to do that in R), that also works. By doing strand(rna) <- "*", I may count extra reads that don't belong to the transcript, for example, if there is a gene transcribing on the opposite strand, overlapping with the gene I am looking at.

Thanks!

**Comment by Roleren** [comment]
To reverse strand, do this: strand(rna) <- ifelse(as.logical(as.character(strand(rna)) == "+"), "-", "+")

Let me know if it does not work :)

**Comment by Roleren** [comment]
I will close this issue if you do not have any more questions ? :)

**Comment by sunyumail93** [comment]
Hi Sure. Thank you! I haven't tried that but I believe it will work. Thanks for helping.
